CREATE OR REPLACE PROCEDURE ADD_DOKUMENTS AS
BEGIN
  DECLARE
    i NUMBER := 1;
  BEGIN
    WHILE i <= 20 LOOP
      INSERT INTO DOKUMENT (ID_DOKUMENTA, ID2_DOKUMENTA, ID3_ZAKAZA, KLIENTS_2ID, DATA_ZAKAZA, DOGOVOR)
      VALUES (i, i+1, i+2, i+3, TO_DATE(TRUNC(DBMS_RANDOM.VALUE(TO_CHAR(TO_DATE('2022-01-01', 'YYYY-MM-DD'), 'J'), TO_CHAR(TO_DATE('2023-12-31', 'YYYY-MM-DD'), 'J'))), 'J'), 'ƒокумент действителен на врем€ оформлени€ заказа');
      i := i + 1;
    END LOOP;
  END;
END ADD_DOKUMENTS;

-- ѕроцедура дл€ удалени€ данных из таблицы DOKUMENT
CREATE OR REPLACE PROCEDURE DELETE_DOKUMENT_DATA (
  P_ID_DOKUMENTA IN NUMBER
) AS
BEGIN
  DELETE FROM DOKUMENT WHERE ID_DOKUMENTA = P_ID_DOKUMENTA;
END DELETE_DOKUMENT;
BEGIN
  DELETE_DOKUMENT(1);
END;
-- ѕроцедура дл€ изменени€ данных в таблице DOKUMENT
CREATE OR REPLACE PROCEDURE UPDATE_DOKUMENT_DATA (
  P_NOMER_DOKUMENTA IN NUMBER,
  P_NOMER_ZAKAZA IN NUMBER,
  P_DATA IN DATE,
  P_KLIENTSKIJ_NOMER IN NUMBER
) AS
BEGIN
  UPDATE DOKUMENT SET NOMER_ZAKAZA = P_NOMER_ZAKAZA, DATA = P_DATA, KLIENTSKIJ_NOMER = P_KLIENTSKIJ_NOMER WHERE NOMER_DOKUMENTA = P_NOMER_DOKUMENTA;
END UPDATE_DOKUMENT_DATA;
BEGIN
  UPDATE_DOKUMENT_DATA(1, 2, TO_DATE('01-FEB-2023', 'DD-MON-YYYY'), 2);
END;
--ѕроцедура дл€ добавлени€ документа
CREATE OR REPLACE PROCEDURE ADD_DOKUMENT_DATA
( P_ID_DOKUMENTA IN NUMBER, P_ID_ZAKAZA IN NUMBER, P_DATA_ZAKAZA IN DATE, P_DOGOVOR IN VARCHAR2(100) )
AS
BEGIN 
FOR i IN 1Е20 LOOP INSERT INTO DOKUMENT (ID_DOKUMENTA, ID1_ZAKAZA, DATA_ZAKAZA, DOGOVOR) 
VALUES (P_ID_DOKUMENTA+i-1, P_ID_ZAKAZA+i, TRUNC(DBMS_RANDOM.VALUE(TO_NUMBER(TO_CHAR(DATE С2022-01-01Т, СJТ)), TO_NUMBER(TO_CHAR(DATE С2023-12-31Т, СJТ)))), Сƒоговор €вл€етс€ действительным на момент заказаТ); END LOOP; END;
/