CREATE TABLE DOKUMENT
(
ID_DOKUMENTA NUMBER(6,0) NOT NULL ENABLE,
ID2_DOKUMENTA NUMBER(6,0),
ID3_ZAKAZA NUMBER(6,0),
KLIENTS_2ID NUMBER(6,0),
DATA_ZAKAZA DATE, DOGOVOR VARCHAR2(100)
CONSTRAINT DOKUMENT_PK PRIMARY KEY (ID2_DOKUMENTA) ENABLE,
CONSTRAINT DOKUMENT_FK1 FOREIGN KEY (ID_DOKUMENTA) REFERENCES FIRMA(ID2_DOKUMENTA),
CONSTRAINT DOKUMENT_FK2 FOREIGN KEY (ID3_ZAKAZA) REFERENCES ZAKAZY(ID_ZAKAZA),
CONSTRAINT DOKUMENT_FK3 FOREIGN KEY (KLIENTS_2ID) REFERENCES KLIENTS(ID2_KLIENTS)
);
/
ALTER TABLE DOKUMENT ADD CONSTRAINT ID_DOKUMENTA_FK FOREIGN KEY (ID_KLIENTS)
REFERENCES KLIENTS (ID) ON DELETE CASCADE ENABLE
/
CREATE OR REPLACE TRIGGER BI_DOKUMENT
before insert on DOKUMENT
for each row
begin
if:NEW. NOMER_DOKUMENTA is null then
select DOKUMENT_SEQ.nextval into:NEW. NOMER_DOKUMENTA from sys.dual;
end if;
end;
/
ALTER TRIGGER BI_DOKUMENT ENABLE;
SELECT * FROM DOKUMENT;
drop table DOKUMENT;