CREATE TABLE FIRMA(
FIRMA_ID NUMBER(6,0) PRIMARY KEY,
NAZVANIE VARCHAR2 (70) NOT NULL ENABLE,
RUKOVODITEL VARCHAR2 (100) NOT NULL ENABLE,
ADRES VARCHAR2 (150),
GLAV_BUH VARCHAR2 (100),
TELEPHONE VARCHAR2 (30),
BIK VARCHAR2 (40) NOT NULL ENABLE,
E_MAIL VARCHAR2 (70),
ID1_VIDA NUMBER(6,0),
ID2_DOKUMENTA NUMBER(6,0),
POSTAVSHIK1_ID NUMBER(6,0),
CONSTRAINT FK_ID1_VIDA FOREIGN KEY (ID1_VIDA) REFERENCES VIDI_USLUG(ID_VIDA),
CONSTRAINT FK_ID2_DOKUMENTA FOREIGN KEY (ID2_DOKUMENTA) REFERENCES DOKUMENT(ID_DOKUMENTA),
CONSTRAINT FK_POSTAVSHIK1_ID FOREIGN KEY (POSTAVSHIK1_ID) REFERENCES POSTAVSHIK(POSTAVSHIK_ID)
);
drop table FIRMA;
SELECT * FROM FIRMA;


INSERT INTO FIRMA (NAZVANIE, RUKOVODITEL, ADRES, GLAV_BUH, TELEPHONE, BIK, E_MAIL)
SELECT NAZVANIE, RUKOVODITEL, ADRES, GLAV_BUH, TELEPHONE, BIK, E_MAIL
FROM JSON_TABLE(BFILENAME('D:\Developer\kursovoi', 'sample1'), '$[*]'
COLUMNS (
NAZVANIE VARCHAR2(70) PATH '$.NAZVANIE',
RUKOVODITEL VARCHAR2(100) PATH '$.RUKOVODITEL',
ADRES VARCHAR2(150) PATH '$.ADRES',
GLAV_BUH VARCHAR2(100) PATH '$.GLAV_BUH',
TELEPHONE VARCHAR2(30) PATH '$.TELEPHONE',
BIK VARCHAR2(40) PATH '$.BIK',
E_MAIL VARCHAR2(70) PATH '$.E_MAIL'
));
