CREATE OR REPLACE PROCEDURE INSERT_POSTAVSHIK (
  POSTAVSHIK_ID_IN NUMBER,
  FIRMA1_ID_IN NUMBER,
  RUKOVODITEL_IN VARCHAR2,
  TELEPHONE_POSTAVSHIKA_IN VARCHAR2,
  BIK_IN NUMBER,
  E_MAIL_IN VARCHAR2
) AS
BEGIN
  INSERT INTO POSTAVSHIK (
    POSTAVSHIK_ID,
    FIRMA_ID,
    RUKOVODITEL,
    TELEPHONE_POSTAVSHIKA,
    BIK,
    E_MAIL
  ) VALUES (
    POSTAVSHIK_ID_IN,
    FIRMA_ID_IN,
    RUKOVODITEL_IN,
    TELEPHONE_POSTAVSHIKA_IN,
    BIK_IN,
    E_MAIL_IN
  );
END;
BEGIN
  INSERT_POSTAVSHIK(1, 1, 'Иван Иванович', '123-45-67', 123456789, 'ivanov@mail.ru');
  INSERT_POSTAVSHIK(2, 2, 'Петр Петрович', '234-56-78', 987654321, 'petrov@mail.ru');
  INSERT_POSTAVSHIK(3, 3, 'Сидор Сидорович', '345-67-89', 192837465, 'sidorov@mail.ru');
END;