CREATE TABLE POSTAVSHIK
(
  POSTAVSHIK_ID NUMBER(10) PRIMARY KEY REFERENCES FIRMA(POSTAVSHIK_ID),
  FIRMA1_ID NUMBER(10) REFERENCES FIRMA(FIRMA_ID),
  RUKOVODITEL VARCHAR2(50),
  TELEPHONE_POSTAVSHIKA VARCHAR2(20),
  BIK_POSTAVSHIKA NUMBER(9,0),
  E_MAIL_POSTAVSHIKA VARCHAR2(20)
);
drop table POSTAVSHIK;

-- —оздание таблицы с маскированными данными
CREATE TABLE masked_POSTAVSHIK (
    POSTAVSHIKm_ID NUMBER(10),
    FIRMA1m_ID NUMBER(10) REFERENCES FIRMA(FIRMA_ID),
    RUKOVODITELm VARCHAR2(50),
    TELEPHONE_POSTAVSHIKAm VARCHAR2(20),
    BIK_POSTAVSHIKAm NUMBER(9,0),
    E_MAILm VARCHAR2(20)
);

-- «аполнение таблицы с маскированными данными
INSERT INTO masked_POSTAVSHIK (POSTAVSHIK_IDm, FIRMA1_IDm, RUKOVODITELm, TELEPHONE_POSTAVSHIKAm, BIK_POSTAVSHIKAm, E_MAIL_POSTAVSHIKAm)
SELECT 
    md5(random()::text),
    md5(random()::text),
    md5(random()::text),
    md5(random()::text),
    md5(random()::text),
    md5(random()::text)
FROM POSTAVSHIK;