CREATE TABLESPACE permanent_tablespace
DATAFILE 'permanent_tablespace_datafile.dbf'
SIZE 100M
AUTOEXTEND ON NEXT 10M
MAXSIZE UNLIMITED;

CREATE TEMPORARY TABLESPACE temporary_tablespace
TEMPFILE 'temporary_tablespace_tempfile.dbf'
SIZE 50M
AUTOEXTEND ON NEXT 10M
MAXSIZE UNLIMITED;


/*Создание профилей безопасности*/
CREATE PROFILE mainHR LIMIT
PASSWORD_LIFE_TIME 90
FAILED_LOGIN_ATTEMPTS 3
PASSWORD_REUSE_TIME 60
PASSWORD_REUSE_MAX 10
PASSWORD_LOCK_TIME 10;

CREATE PROFILE HRmanagger LIMIT
PASSWORD_LIFE_TIME 120
FAILED_LOGIN_ATTEMPTS 5
PASSWORD_REUSE_TIME 90
PASSWORD_REUSE_MAX 15
PASSWORD_LOCK_TIME 5;

CREATE PROFILE site_user LIMIT
PASSWORD_LIFE_TIME 180
FAILED_LOGIN_ATTEMPTS 7
PASSWORD_REUSE_TIME 120
PASSWORD_REUSE_MAX 20
PASSWORD_LOCK_TIME 1;


/*Создание ролей*/
CREATE ROLE mainHR_role;
CREATE ROLE HRmanagger_role;
CREATE ROLE site_user_role;

/*Выдача привелегий ролям*/
GRANT SELECT, INSERT, DELETE, UPDATE ON site_user TO mainHR;
GRANT SELECT, INSERT, DELETE, UPDATE ON HRmanagger TO mainHR;
GRANT SELECT, INSERT, DELETE, UPDATE ON DOKUMENT TO mainHR;

GRANT SELECT, UPDATE ON site_user TO HRmanagger;
GRANT SELECT, UPDATE ON KLIENTS TO HRmanagger;
GRANT SELECT, UPDATE ON FIRMA TO HRmanagger;
GRANT SELECT, UPDATE ON USLUGI TO HRmanagger;
GRANT SELECT, UPDATE ON VIDI_USLUG TO HRmanagger;

GRANT SELECT, UPDATE ON ZAKAZ TO site_user;
GRANT SELECT ON USLUGI TO site_user;

/*Создание пользователей*/
CREATE USER mainHR_user IDENTIFIED BY mainHR_password
DEFAULT TABLESPACE my_tablespace
TEMPORARY TABLESPACE my_temp_tablespace
PROFILE mainHR_profile;

CREATE USER HRmanagger_user IDENTIFIED BY HRmanagger_password
DEFAULT TABLESPACE my_tablespace
TEMPORARY TABLESPACE my_temp_tablespace
PROFILE HRmanagger_profile;