CREATE TABLE USLUGI
(
ID_USLUGI NUMBER (6,0) NOT NULL ENABLE,
USLUGA VARCHAR2 (60) NOT NULL ENABLE,
PRICE NUMBER NOT NULL ENABLE,
ID_VIDA3 NUMBER (6,0) NOT NULL ENABLE,
VID_USLUGI NUMBER (6,0),
CONSTRAINT USLUGI_PK PRIMARY KEY (ID_USLUGI) ENABLE,
CONSTRAINT FK_USLUGI_VIDI FOREIGN KEY (ID_VIDA) REFERENCES VIDI_USLUG(ID_VIDA)
);
SELECT * FROM USLUGI;
drop table USLUGI;
/
ALTER TABLE USLUGI ADD CONSTRAINT USLUGI_FK FOREIGN KEY (KOD_VIDA)
REFERENCES VIDI_USLUG (KOD) ON DELETE CASCADE ENABLE
/
CREATE OR REPLACE TRIGGER BI_USLUGI
BEFORE INSERT ON USLUGI
FOR EACH ROW
BEGIN
IF:NEW. KODIS IS NULL THEN
SELECT USLUGI_SEQ1.NEXTVAL INTO:NEW. KOD FROM SYS.dual;
END IF;
END;
/
ALTER TRIGGER BI_USLUGI ENABLE;
/
/*Сериализация в JSON*/
DECLARE
  s_file UTL_FILE.FILE_TYPE;
BEGIN
  s_file := UTL_FILE.FOPEN('DIRECTORY_NAME', 'sample1.json', 'W');
  FOR i IN (SELECT JSON_SERIALIZE(COLUMN_VALUE) FROM USLUGI) LOOP
    UTL_FILE.PUT_LINE(s_file, i.COLUMN_VALUE);
  END LOOP;
  UTL_FILE.FCLOSE(s_file);
END;


/*Реализация скидок*/
CREATE TABLE USLUGI_SKIDKI (
  ID NUMBER(10) PRIMARY KEY,
  NAZVANIE VARCHAR2(50),
  CENA NUMBER(10),
  SKIDKA NUMBER(10)
);

CREATE OR REPLACE TRIGGER TRG_USLUGI_SKIDKI
BEFORE INSERT ON USLUGI_SKIDKI
FOR EACH ROW
DECLARE
  V_COUNT NUMBER(10);
BEGIN
  SELECT COUNT(*) INTO V_COUNT FROM USLUGI_SKIDKI WHERE ID = :NEW.ID;
  IF MOD(V_COUNT, 3) = 0 THEN
    :NEW.SKIDKA := :NEW.CENA * 0.2;
  ELSE
    :NEW.SKIDKA := 0;
  END IF;
END;