/*Количество заказов по группам товаров*/
CREATE OR REPLACE FORCE VIEW KOL_ZAKAZOV_PO_GRUPPAM_TOVAROV (DATA, VID, KOLICHESTVO_ZAKAZOV) AS
SELECT DOKUMENT.DATA, VIDI_USLUG.VID, SUM (ZAKAZ.KOLICHESTVO) AS KOLICHESTVO_ZAKAZOV
FROM VIDI_USLUG INNER JOIN (USLUGI INNER JOIN (DOKUMENT INNER JOIN ZAKAZ ON DOKUMENT.NOMER_DOKUMENTA=ZAKAZ.NOMER_DOKUMENTA) ON USLUGI.KOD=ZAKAZ.KOD_USLUGI) ON VIDI_USLUG.KOD=USLUGI.KOD_VIDA
GROUP BY DOKUMENT.DATA, VIDI_USLUG.VID;
/*Стоимость и количество продаж по услугам и товарам*/
CREATE OR REPLACE FORCE VIEW STOIM_I_KOL_PRODAG_PO_TOVARAM (DATA, USLUGA, VIRUCHKA, KOLICHESTVO_ZAKAZOV) AS
SELECT DOKUMENT.DATA, USLUGI.USLUGA, SUM (USLUGI.PRICE*ZAKAZ.KOLICHESTVO) AS VIRUCHKA, SUM (ZAKAZ.KOLICHESTVO) AS KOLICHESTVO_ZAKAZOV
FROM USLUGI INNER JOIN (DOKUMENT INNER JOIN ZAKAZ ON DOKUMENT.NOMER_DOKUMENTA=ZAKAZ.NOMER_DOKUMENTA) ON USLUGI.KOD=ZAKAZ.KOD_USLUGI
GROUP BY DOKUMENT.DATA, USLUGI.USLUGA, USLUGI.PRICE, ZAKAZ.STATUS
HAVING (ZAKAZ.STATUS='выполнен')
ORDER BY DOKUMENT.DATA;
/*Выручка по дням*/
CREATE OR REPLACE FORCE VIEW VIRUCHKA_PO_DNYAM (DATA, VIRUCHKA) AS
SELECT DOKUMENT.DATA, SUM (USLUGI.PRICE*ZAKAZ.KOLICHESTVO) AS VIRUCHKA
FROM DOKUMENT INNER JOIN (USLUGI INNER JOIN ZAKAZ ON USLUGI.KOD=ZAKAZ.KOD_USLUGI) ON DOKUMENT.NOMER_DOKUMENTA=ZAKAZ.NOMER_DOKUMENTA
GROUP BY DOKUMENT.DATA;
/