CREATE TABLE ZAKAZ
(
  ID_ZAKAZA NUMBER(6,0) PRIMARY KEY,
  ID3_USLUGI NUMBER(6,0) NOT NULL,
  KOLICHESTVO NUMBER(6,0) NOT NULL,
  STATUS VARCHAR2(50),
  NOMER_DOKUMENTA NUMBER(6,0),
  ID1_KLIENT NUMBER(6,0),
  CONSTRAINT FK_DOKUMENT FOREIGN KEY (NOMER_DOKUMENTA) REFERENCES DOKUMENT(ID_DOKUMENTA),
CONSTRAINT FK_KLIENT FOREIGN KEY (ID1_KLIENT) REFERENCES KLIENT(ID_KLIENT)
);
/
ALTER TABLE ZAKAZ ADD CONSTRAINT ZAKAZ_FK2 FOREIGN KEY (NOMER_DOKUMENTA)
REFERENCES DOKUMENT (NOMER_DOKUMENTA) ON DELETE CASCADE ENABLE
/
ALTER TABLE ZAKAZ ADD CONSTRAINT ZAKAZ_FK3 FOREIGN KEY (KOD_USLUGI)
REFERENCES USLUGI (KOD) ON DELETE CASCADE ENABLE
/
SELECT * FROM ZAKAZ;
drop table ZAKAZ;