CREATE OR REPLACE PROCEDURE ADD_ZAKAZ_DATA_NEW (ID_DOKUMENTA IN NUMBER, ID_USLUGI IN NUMBER, KOLICHESTVO IN NUMBER, STATUS IN VARCHAR2)
AS
BEGIN
  INSERT INTO ZAKAZ_NEW (ID_ZAKAZA, ID3_USLUGI, KOLICHESTVO, STATUS, ID_DOKUMENTA) VALUES (ZAKAZ_NEW_SEQ.NEXTVAL, ID_USLUGI, KOLICHESTVO, STATUS, ID_DOKUMENTA);
  COMMIT;
END;
BEGIN
  FOR i IN 1..18 LOOP
    ADD_ZAKAZ_DATA_NEW(i, i+1, TRUNC(DBMS_RANDOM.VALUE(1, 5)), 'В обработке', i);
  END LOOP;
END;
BEGIN
  FOR i IN 18..28 LOOP
    ADD_ZAKAZ_DATA_NEW(i, i+1, TRUNC(DBMS_RANDOM.VALUE(1, 5)), 'Завершён', i);
  END LOOP;
END;
BEGIN
  FOR i IN 29..30 LOOP
    ADD_ZAKAZ_DATA_NEW(i, i+1, TRUNC(DBMS_RANDOM.VALUE(1, 5)), 'На стадии оформления', i);
  END LOOP;
END;

-- Процедура для удаления данных из таблицы ZAKAZ
CREATE OR REPLACE PROCEDURE DELETE_ZAKAZ_DATA (NOMER_DOKUMENTA IN NUMBER)
AS
BEGIN
  DELETE FROM ZAKAZ WHERE NOMER_DOKUMENTA = NOMER_DOKUMENTA;
  COMMIT;
END;
BEGIN
  DELETE_ZAKAZ_DATA(1);
END;

-- Процедура для обновления данных в таблице ZAKAZ
CREATE OR REPLACE PROCEDURE UPDATE_ZAKAZ_DATA (NOMER_DOKUMENTA IN NUMBER, KOD_USLUGI IN NUMBER, KOLICHESTVO IN NUMBER, STATUS IN VARCHAR2)
AS
BEGIN
  UPDATE ZAKAZ SET KOD_USLUGI = UPDATE_ZAKAZ_DATA.KOD_USLUGI, KOLICHESTVO = UPDATE_ZAKAZ_DATA.KOLICHESTVO, STATUS = UPDATE_ZAKAZ_DATA.STATUS WHERE NOMER_DOKUMENTA = UPDATE_ZAKAZ_DATA.NOMER_DOKUMENTA;
  COMMIT;
END;
BEGIN
  UPDATE_ZAKAZ_DATA(15, 16, 2, 'На стадии Оформления');
  END;
  BEGIN
  UPDATE_ZAKAZ_DATA(2, 3, 4, 'На стадии оформления');
  UPDATE_ZAKAZ_DATA(3, 4, 5, 'Завершен');
  BEGIN
  FOR i IN 8..12 LOOP
    UPDATE_ZAKAZ_DATA(i, i+1, TRUNC(DBMS_RANDOM.VALUE(1, 5)), 'На стадии оформления');
  END LOOP;
END;
END;